version: '3.9'

services:
  web:
    container_name: placdesk1
    build: ./src
    command: uvicorn app.main:app --workers 1 --host 0.0.0.0 --port 8010
    volumes:
      - type: bind
        source: ./src/
        target: /usr/src/app/
    ports:
      - target: 8010
        published: 7001
        protocol: tcp
        mode: host
    environment:
      DATABASE_URL: postgresql://placdesk:placdesk@db:5432/placdesk

  db:
    image: postgres:12.1-alpine
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data
    ports:
      - "5433:5432"  # Map port 5432 inside the container to port 5433 on the host
    environment:
      POSTGRES_USER: placdesk
      POSTGRES_PASSWORD: placdesk
      POSTGRES_DB: placdesk

volumes:
  postgres_data:

networks:
  default:
    name: plac-net
    external: true

